<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Demo.WinFormCalculator\bin\**" />
    <Compile Remove="Demo.WinFormCalculator\obj\**" />
    <Compile Remove="Demo.WinFormCalculator\Properties\**" />
    <Compile Remove="net90\**" />
    <Content Remove="Demo.WinFormCalculator\bin\**" />
    <Content Remove="Demo.WinFormCalculator\obj\**" />
    <Content Remove="Demo.WinFormCalculator\Properties\**" />
    <Content Remove="net90\**" />
    <EmbeddedResource Remove="Demo.WinFormCalculator\bin\**" />
    <EmbeddedResource Remove="Demo.WinFormCalculator\obj\**" />
    <EmbeddedResource Remove="Demo.WinFormCalculator\Properties\**" />
    <EmbeddedResource Remove="net90\**" />
    <None Remove="Demo.WinFormCalculator\bin\**" />
    <None Remove="Demo.WinFormCalculator\obj\**" />
    <None Remove="Demo.WinFormCalculator\Properties\**" />
    <None Remove="net90\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Demo.WinFormCalculator\Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Demo.WinFormCalculator\CalculatorForm.cs" />
    <Content Remove="wwwroot\Demo.WinFormCalculator\CalculatorForm.Designer.cs" />
    <Content Remove="wwwroot\Demo.WinFormCalculator\WasmProgram.cs" />
    <Content Remove="wwwroot\_framework\DCResourceStrings-en.js" />
    <Content Remove="wwwroot\_framework\DCResourceStrings-zh.js" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="wwwroot\Demo.WinFormCalculator\CalculatorForm.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="wwwroot\Demo.WinFormCalculator\CalculatorForm.Designer.cs" />
    <Compile Include="wwwroot\Demo.WinFormCalculator\WasmProgram.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\_framework\DCResourceStrings-en.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\_framework\DCResourceStrings-zh.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.11" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Lib\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DCSoft.WinForm2WASM">
      <HintPath>Lib\DCSoft.WinForm2WASM.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="published\Demo.WinFormCalculator\CalculatorForm.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="readme.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
